FROM node:16-alpine

RUN mkdir -p /usr/src/app/src && mkdir -p /usr/src/app/public

WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
COPY src/ /usr/src/app/src/
COPY public/ /usr/src/app/public/

ENV WDS_SOCKET_PORT=0

RUN yarn install

EXPOSE 9000

CMD ["yarn", "start"]
